# Generated by Django 4.2.2 on 2023-06-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="course_category",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
