# Generated by Django 4.2.2 on 2023-06-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_training_course_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("course_id", models.IntegerField()),
            ],
        ),
    ]
