# Generated by Django 4.2.2 on 2023-06-19 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0006_carttraining"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carttraining",
            name="course_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.training"
            ),
        ),
        migrations.AlterField(
            model_name="carttraining",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
