# Generated by Django 4.2.2 on 2023-06-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_carttraining_course_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carttraining", name="course_id", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="carttraining", name="user_id", field=models.IntegerField(),
        ),
    ]
