# Generated by Django 4.2.2 on 2023-06-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_consulting"),
    ]

    operations = [
        migrations.AddField(
            model_name="consulting",
            name="cons_price",
            field=models.IntegerField(null=True),
        ),
    ]
