# Generated by Django 4.2.2 on 2023-06-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_consulting_cons_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Webstore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("web_name", models.CharField(max_length=100)),
                ("web_desc", models.TextField()),
                ("web_price", models.IntegerField(null=True)),
                ("web_author", models.CharField(max_length=100)),
                ("web_rating", models.IntegerField()),
                ("web_category", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="consulting",
            name="cons_category",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="training",
            name="course_rating",
            field=models.IntegerField(null=True),
        ),
    ]
