# Generated by Django 4.2.2 on 2023-06-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_webstore_consulting_cons_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartWebstore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("course_id", models.IntegerField()),
            ],
        ),
    ]
